import turtle
t=turtle.Pen()
turtle.bgcolor("black")
t.speed(0)
t.width(4)
# Ask the user for the number of circles in their rosette, default to 6.
number_of_circles = int(turtle.numinput("Number of circles",
                                        "How many circles in your rosette?", 6))
for x in range(number_of_circles):
    t.pencolor("pink")
    t.circle(300)
    t.pencolor("yellow")
    t.circle(290)
    t.pencolor("white")
    t.circle(280)
    t.pencolor("orange")
    t.circle(270)
    t.pencolor("blue")
    t.circle(260)
    t.pencolor("light green")
    t.circle(250)
    t.pencolor("gold")
    t.circle(240)
    t.pencolor("purple")
    t.circle(230)
    t.pencolor("magenta")
    t.circle(220)
    t.pencolor("brown")
    t.circle(210)
    t.pencolor("red")
    t.circle(200)
    t.pencolor("indigo")
    t.circle(190)
    t.pencolor("grey")
    t.circle(180)
    t.pencolor("green")
    t.circle(170)
    t.pencolor("black")
    t.circle(160)
    t.pencolor("silver")
    t.circle(150)
    t.pencolor("sky blue")
    t.circle(140)
    t.left(360/number_of_circles)
